project:
  type: book
  output-dir: docs

book:
  title: "Collective & Open Research in Climate Science"
  author: "Angelo Varlotta"

  sidebar: 
    style: docked
    search: true
    background: light

  page-footer: 
      left: "Collective and Open Research in Climate" 
      right: 
        - icon: github
          href: https://github.com/varlottaang/collective-and-open-research-in-climate

  page-navigation: true
  search: true
  repo-url: https://github.com/varlottaang/collective-and-open-research-in-climate
  repo-actions: [edit, issue]
  sharing: [facebook, twitter]

  date: "4/4/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    
format:
  html:
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png
    
bibliography: references.bib

comments:
  hypothesis: true