# Preface {.unnumbered}

# Collective & Open Research in climate science

### Project
The idea is to facilitate the creation of an environment (a working group or a community, eventually) where researchers, students, citizen scientists can collaborate on projects, research projects, articles or just share their work based on open science principles.
There are examples of open research environments in the scientific community, in particular in the machine learning field.
Examples are [mlcollective](https://mlcollective.org/), [Machine Learning Tokyo](https://machinelearningtokyo.com/) and [Neuromatch Academy](https://academy.neuromatch.io/).
Those communities run by volunteers created a friendly environment and study groups for machine learning practitioners and also curricula to introduce students to data science.
In e.g., the [mlcollective](https://mlcollective.org/projects/) effort led to the publication of many projects.

Eventually, these examples could be used to create or simply design (white paper/report) a similar project in other research areas.

### Problem
It’s hard for newcomers, especially students, to get involved in research. That’s why I would like to create a collaborative environment/guidelines/frameworks in the climate sciences field.

The project aims to create an infrastructure that can lead to the creation of an open research collective.
The problems to solve are:

* Understanding the climate change scenario (other open science projects, initiatives, papers…)
* How to create a friendly environment for researchers, students and newcomers (Tools and instruments)
* How to eventually manage research data and publish results (on diamond open access?)
* Ethical problems in the climate sciences ladscape

### Achievements
Learn how to work in open science, and communicate findings to a broader audience. The idea is to create a white paper or final report about the status of open research and open groups in climate change and health. Even if at the end of the study period we don’t have a working collective (very likely), a white paper/report could lead to the creation of one in the future and could be the initial framework for other groups.

